steps:

# Build your app using Cloud Build and Buildpacks.io & Push it to Google Artifact Registry! 
- name: 'gcr.io/k8s-skaffold/pack'
  entrypoint: 'pack'
  args: ['build','--builder=gcr.io/buildpacks/builder', 
  '--publish', 'us-central1-docker.pkg.dev/hamzalabs/petclinic-artifact-repo/petclinic:latest']

# Deploy your app using Cloud Build to Google Cloud Run!!
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'petclinic', '--image', 'us-central1-docker.pkg.dev/hamzalabs/petclinic-artifact-repo/petclinic:latest',
  '--region', 'us-central1', '--allow-unauthenticated', 
   '--cpu=2', '--memory=512M',
  '--service-account', 'SERVICE_ACCOUNT_ID@PROJECT_ID.iam.gserviceaccount.com', 
  '--add-cloudsql-instances=connection_name_of_yourDB']


